### PR TITLE
Fix waveguide dims inputs

### PR DESCRIPTION
**Pull request by ajnonaka**
remove geom.coord_sys and add geom.dims to inputs files in Examples/Waveguide

### CODE REVIEW

**Review by RevathiJambunathan — APPROVED** [review]
thank you for this PR

**Review by saurabh-s-sawant — COMMENTED** [review]
There seem to be some issue with AMR_ParmParse when I try to run Waveguide/inputs_3d_LLG_filter.
The backtrace takes me to line 906 in /home/saurabh/LBNLWork/Codes/amrex/Src/Base/AMReX_ParmParse.cpp
which requires mag_M_normalization. However, this is defined in the input file!!
I am not sure the cause of the error. Could you please check?

Same issue with Waveguides/inputs_3d_empty_X_band.

Waveguides/inputs_regression_3d_LLG_filter runs fine.

**Comment by ajnonaka** [comment]
The problem in inputs_3d_LLG_filter is in the lines with "diag_lo" and "diag_hi" at the bottom of the file.  These are the lines that let your plot out a subregion of the full dataset.  If I comment out those two lines the code runs.  I don't know why yet.

**Comment by ajnonaka** [comment]
The ParmParse issue will be resolved with WarpX [#2799](https://github.com/ECP-WarpX/WarpX/pull/2799/files).  @RevathiJambunathan can you merge this now so we can at least use the inputs without the sub-plot feature?

**Pull request merged**
