### PR TITLE
Fft time

### PR DESCRIPTION
**Pull request by jackieyao0114**

### CODE REVIEW

**Review by RevathiJambunathan — CHANGES_REQUESTED** [review]
I am just seeing this and here are some first look comments. 

I see that some *.png files are includes here. Can we not add them to the PR and merge to repository? Also please can you add the *.ipynb files in `Tools/Postprocessing/` 
What is the difference between circuit_fft.ipynb and circuit_fft_ajn.ipynb? 
For the latter notebook, I see that there are some files loaded from scratch. Would be best to make this general. 

Is the main objective of this PR to add the FFT python notebook?
Or both input script and FFT python notebook?

**Comment by ajnonaka** [comment]
inputs_pd_curved
inputs_roger
Parameters for inputs_pd_curved and inputs_roger

**Comment by ajnonaka** [comment]
inputs_maurice
Parameters for inputs_maurice

**Comment by ajnonaka** [comment]
Image from iOS

**Comment by ajnonaka** [comment]
Closing, as all the diagnostic development work over the past few months has eliminated the need for this style of post-processing.

**Pull request closed without merging**
