### PR TITLE
Time varying hbias

### PR DESCRIPTION
**Pull request by jackieyao0114**
We sometimes need time varying H_bias, primarily for two scenarios:
1. H_maxwell is included in H_bias for the one-way coupling that Jordan's working on;
2. H_bias needs to be turned on/off at certain time points; Note: H_bias is still DC in this case, it just changes as a step function when needed.

### CODE REVIEW

**Comment by ajnonaka** [comment]
We should close this an open a different PR
jackie/FixExcitationBC <- jackie/TimeVaryingHbias
So this PR only contains the changes due to time-dependent H_bias

**Comment by RevathiJambunathan** [comment]
looks good to me. @jackieyao0114 can you also please add the corresponding documentation for this input parameter. Thank you

**Comment by ajnonaka** [comment]
Do we need a call to ApplyExternalFieldExcitationOnGrid(ExternalFieldType::HbiasfieldExternal) somewhere in WarpXEvolve.cpp?

**Review by RevathiJambunathan — APPROVED** [review]
Thanks for the PR!

**Review by ajnonaka — APPROVED** [review]

**Pull request merged**
